- app/adapters/application.js
- app/controllers/browse.js
- app/models/package_category.js
- app/router.js
- app/routes/browse.js
- app/templates/application.hbs
- app/templates/browse.hbs
- bower.json
- ember-cli-build.js
- package.json
Thanks @mcm-ham 
Fix error loading ember-data, remove deprecated code
* Brocfile has been replaced by ember-cli-build
* Remove import of ember-data in ember-cli-build because the ember-data node package already does this
* LRPortOverride environment variable has been replaced by ember command line switch
* Update ember-data to current nightly build (replace with ember-data beta 2 when released) to fix usage of fixture-adapter.js#Ember.ArrayPolyfills.indexOf that's been removed in Ember 2.0 beta 2
* Replace deprecated usage of store.find with store.findAll
* Add active-model-adapter addon since it's been moved out of ember-data
> Initial app setup and Browse Page

- app/components/select-list.js
- app/controllers/package_category.js
- app/helpers/is-equal.js
- app/helpers/is-not.js
- app/models/item.js
- app/models/package_category.js
- app/router.js
- app/routes/application.js
- app/routes/package_category.js
- app/templates/application.hbs
- app/templates/browse.hbs
- app/templates/components/select-list.hbs
- app/templates/package_category.hbs
- app/templates/sidebar.hbs
- config/environment.js
This PR has:
- sort items based on sub-categories
- sort items based on 'newest-first' and 'oldest-first' criteria
> Gcw 445 browse items in a category

- app/controllers/item.js
- app/models/item.js
- app/styles/templates/_item.scss
- app/templates/item.hbs
- tests/unit/models/item-test.js
Hi Team,
This PR is to change layout of item view.
Thanks
> GCW-1252-change-layout-of-item-view

- app/components/image-preview.js
- app/models/item.js
- app/styles/_sidebar.scss
- app/styles/templates/_item.scss
- app/styles/templates/_package_category.scss
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/components/image-preview.hbs
- app/templates/item.hbs
- bower.json
- ember-cli-build.js
Hi,
This PR contains lightgallery version changes and image layout changes for small screen.
Thanks.
> GCW-1252-image-layout-changes-for-small-screen

- app/controllers/application.js
- app/controllers/item.js
- app/controllers/subscription.js
- app/models/cart_item.js
- app/models/item.js
- app/models/package.js
- app/models/package_type.js
- app/services/cart.js
- app/styles/_cart_sidebar.scss
- app/templates/_desktop_cart_sidebar.hbs
- app/templates/cart_content/_checkout_full_view.hbs
- app/templates/cart_content/_checkout_small_view.hbs
- app/templates/cart_content/_full_view.hbs
- app/templates/cart_content/_items.hbs
- app/templates/components/small-cart-toggle-view.hbs
- Update Cart when package
- dispatched
- unpublished
(Changes still remaining if any changes in item-packages)
> Update cart items availability

- .gitignore
- Rakefile
- circle.yml
- cordova/config.xml
- cordova/deploy/testfairy-android-upload.sh
- cordova/scripts/update_build_number.py
- fastlane/Appfile
- fastlane/Fastfile
- fastlane/README.md
- package.json
- scripts/install-provisioning-file.sh
@steveyken - I have uploaded provisioning files to Azure.
> CircleCI OS X Build

- .codeclimate.yml
- Gemfile
- circle.yml
- package.json
- yarn.lock
Added Fastlane and Credential manager gem in gemfile
Also added ember-cli in circleci file as it was not there where as we are using that in all other project files.
> Added code to support code coverage on Code climate

- config/environment.js
Hi Team,
This PR contains changes to exclude transition aborted error in rollbar
Thanks
> #DecemberRelease2

- app/controllers/application.js
- app/controllers/order/confirm.js
- app/controllers/order/transport_details.js
- app/controllers/order_details.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/services/cart.js
- app/templates/order/_alert_item_not_available.hbs
- app/templates/order/confirm.hbs
- app/templates/order/transport_details.hbs
- app/templates/order_details.hbs
Hi Team,
This PR contains changes for if any item is unavilable from cart then we will be showing popup msg to remove items from cart and then proceed.
Thanks.
> Gcw 1755 browse order submission breaks

- app/services/cart.js
Hi Team,
This PR contains fix for https://jira.crossroads.org.hk/browse/GCW-1818(Browse App: TypeError: Cannot read property 'toJSON' of null)
> GCW-1818 remove item from cart issue

- app/controllers/order_details.js
Reverts crossroads/browse.goodcity#137
> Revert "GCW-1825 Cannot read property get of null"

- app/controllers/order/confirm.js
- app/services/cart.js
- app/templates/order/_alert_item_not_available.hbs
- app/templates/order/confirm.hbs
Hi Team,
This PR contains changes for GCW:1824:- Fix one or more items no available in your cart pop-up showing on submitting an order
Jira:- https://jira.crossroads.org.hk/browse/GCW-1824
> GCW:1824 One or many item not available pop-up fix

- app/controllers/application.js
- app/controllers/authenticate.js
- app/controllers/browse.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/styles/_settings.scss
- app/styles/_sidebar.scss
- app/templates/sidebar.hbs
Hi Team,
This PR adds logout feature to Browse App.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1877
> GCW-1877 Logout added to Browse App

- app/routes/package_category.js
- tests/acceptance/item-test.js
- tests/factories/item.js
- tests/factories/package.js
- tests/factories/package_category.js
Hi Team,
This PR increases Browse App code coverage by 6.6%
> Test cases added

- app/controllers/browse.js
- app/controllers/subscription.js
- app/models/package.js
- app/models/package_category.js
- app/models/package_type.js
Hi Team,
This PR fixes GCW:1890:- Browse App: Publishing package for first time doesn't show up
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1890
> GCW-1890 Publishing first package on browse doesnt show up

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/router.js
- app/styles/_ember_offline.scss
- app/templates/not-found.hbs
Hi Team,
This PR adds not-found page.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1943
> GCW:1943 Not found page

- app/controllers/order/transport_details.js
- app/controllers/order_details.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/order.js
- app/models/orders_purpose.js
- app/models/purpose.js
- app/routes/order_details.js
- app/templates/order/transport_details.hbs
- app/templates/order_details.hbs
- tests/unit/models/order-test.js
Hi Team,
This PR adds functionality of editing order and transport detail for Draft Orders.
Jira ticket link:- https://jira.crossroads.org.hk/browse/GCW-1941
> GCW 1941 draft order edit

- app/controllers/order/transport_details.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/styles/_transport_details.scss
- app/templates/order/_cancel_order.hbs
- app/templates/order/_ggv_form.hbs
- app/templates/order/_self_vehicle_form.hbs
Hi Team,
This PR adds functionality to delete draft Order.
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-1942
> GCW:1942 Order cancellation

- app/controllers/application.js
- app/controllers/subscription.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/orders_package.js
- app/routes/post_login.js
- app/styles/_my_orders.scss
- app/templates/cart_content/_full_view.hbs
Hi, 
This is PR for GCW-1936,GCW-1937 and GCW-1939
Thanks
> Gcw 1932 user can delete item from draft order

- app/routes/post_login.js
Hi, 
This is PR for GCW-1939 cart merge issue
Thanks
> filtered orders_packages merged with cart

- tests/acceptance/browse-test.js
- tests/factories/gogovan_transport.js
- tests/factories/user.js
- tests/factories/user_role.js
- tests/helpers/start-app.js
Hi,
This is PR for GCW-1936- clear orders and orders_packages from ember data after logout.
Thanks
> Gcw 1936 clear order and orders packages

- app/controllers/application.js
- app/controllers/browse.js
- app/controllers/my_orders.js
- app/controllers/order/confirm.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/browse.js
- app/routes/my_orders.js
- app/services/flash-message.js
- app/styles/templates/_application.scss
- app/templates/application.hbs
Hi Team,
This PR adds flash messages when an Order is cancelled or submitted.
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1944
> GCW-1944 Flash message

- app/controllers/browse.js
- app/controllers/my_orders.js
- app/routes/browse.js
- app/routes/my_orders.js
Hi Team,
This PR fixes repeated flash message issue.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2008
> GCW-2008 repeated flash message bug

- app/controllers/order/transport_details.js
- app/models/order_transport.js
- app/routes/order/transport_details.js
Hi Team,
This PR includes feature of transport_detail page pre-filled if it was already filled up user.
Transport detail stays the same even after refreshing the page.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2009
> GCW 2009 transport detail reset

- app/controllers/application.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/_confirm_order.hbs
Hi Team,
This PR is for adding internationalisation for `Transport Method` and Item no longer available pop-up.
https://jira.crossroads.org.hk/browse/GCW-2030
Please review and let me know if any changes are required.
Thanks.
> add translations

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/_confirm_order.hbs
Hi Team, 
This PR is to remove colon from hbs file and to add it to translations file.
Please review and let me know if any changes required.
Thanks.
> move colon to transations file

- app/locales/zh/translations.js
Hi Team,
This PR is to add chinese translation of `You are not authorized.` string.
https://jira.crossroads.org.hk/browse/GCW-2030
Thanks.
> added chinese translation for unauthozed msg

- Rakefile
- circle.yml
- cordova/config.xml
- package.json
Hi Team,
This PR upgrades:
- XCode to 9.2
- Cordova to latest
- Cordova-ios to 4.5.4
For more detail description please refer PR: https://github.com/crossroads/stock.goodcity/pull/269
Please review this PR and let me know if anymore changes are required.
Thanks
> GCW-1999 Xcode upgrade to 9.2

- app/controllers/application.js
- config/environment.js
- tests/acceptance/cart-test.js
- tests/factories/order.js
- tests/factories/orders_package.js
- tests/factories/orders_purpose.js
- tests/factories/package.js
- tests/factories/package_type.js
Hi,
This is PR for GCW-1937 test case.
Thanks
> Gcw 1937 deleting orders packages from draft order

- app/locales/en/translations.js
Hi,
This is PR for GCW-2020-Typo error in transport details page. https://jira.crossroads.org.hk/browse/GCW-2020.
Thanks
> minor typo removed

- app/controllers/item.js
Hi Team,
This PR fixes issue of side cart not opening sometimes.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2072
Please review it and let me know if any changes are required.
Thanks
> GCW:2072 Side cart open issue fixed

- app/controllers/subscription.js
- app/models/package.js
Hi Team,
This PR fixes live update issue of sync between StockIt and Browse.
Jira tickets:- https://jira.crossroads.org.hk/browse/GCW-2077, https://jira.crossroads.org.hk/browse/GCW-2079
Please review it and let me know if any more changes are required.
Thanks
> GCW:2079 GCW:2077 live update fix

- app/controllers/order/transport_details.js
- tests/acceptance/browse-test.js
- tests/acceptance/cart-test.js
- tests/factories/organisation.js
- tests/factories/user.js
Hi Team,
This is PR for Jira ticket GCW-1938.
https://jira.crossroads.org.hk/browse/GCW-2038.
I have handled the skipping empty field scenario of userName and mobilePhone.
Please let me know if any change is required.
Thanks.
> empty name and mobile field validation added

- app/index.html
- cordova/config.xml
Hi Team,
This PR fixes status-bar issue for mobile app.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2110
Please review it and let me know if any other changes are required.
Thanks
> GCW-2110 Statusbar fix

- app/styles/_transport_details.scss
- app/styles/templates/_login.scss
Hi Team,
This PR fixes Transport detail page css.
Please review it and let me know if any other changes are required.
thanks
> Transport detail css fix

- app/controllers/application.js
- tests/acceptance/cart-test.js
- tests/factories/orders_package.js
Hi Team,
This is PR for jira ticket GCW-2111- Deleting newly added package in order in draft state gives error.
https://jira.crossroads.org.hk/browse/GCW-2111.
I have added the fix. Please review the PR and let me know.
Thanks.
> package exist in order in draft check added before deleting

- Gemfile.lock
Hi Team,
This PR fixes a ruby-zip vulnerability. 
Please review.
Thanks.
> fix ruby-zip vulnerability

- app/styles/components/_logo-banner.scss
- app/styles/templates/_home.scss
- app/templates/home.hbs
Text should not overflow off the screen anymore, and the content should shift left when the sidebar is open on the right side
> Homepage responsive fixes

- app/routes/item.js
Hi Team,
This PR fixes rollbar issue for item does not exist
RollBar link:- https://rollbar.com/crossroads_it/browse.goodcity/items/281/
> RollBar fix

- app/controllers/item.js
- app/styles/_pagination.scss
- app/styles/_sidebar.scss
- app/styles/templates/_home.scss
- app/templates/application.hbs
- app/templates/home.hbs
- app/templates/item.hbs
Adapt the layout to the sidebar : shifts left only if sidebar is active
@Darshan-Chauhan any more changes you wish to add ?
> Itunes cert responsive changes

- app/routes/application.js
- app/routes/session.js
Hi Team,
This PR is for continuous reloading issue on IE. It has been fixed. 
Please review it and let me know if any change is required.
Thanks
> Fixed: Continuous reloading issue on IE fixed

- app/controllers/order/confirm.js
Hi Team,
This PR has some refactoring and fixes issue of Item can be ordered twice.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2180
Please review it and let me know if any changes are required.
Thanks
> GCW-2180 Item can be ordered twice issue fix

- app/controllers/item.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/package.js
- app/models/user.js
- app/services/session.js
- app/styles/_my_orders.scss
- app/templates/item.hbs
- config/environment.js
- tests/acceptance/item-test.js
- tests/factories/package.js
- tests/factories/role.js
Hi Team,
This is PR for GCW-2153- adding inventory number on browse to redirect user to stock app on inventory number Item for Order Fulfilment role user.
https://jira.crossroads.org.hk/browse/GCW-2153
- I have added the fix and also added test case for the same.
- Will be creating separate ticket for the mobile deep linking i.e app to app navigation.
Let me know if any change is required.
Thanks
> Fixed:GCW 2153- display inventory number added

- app/controllers/account_details.js
- app/locales/en/translations.js
- app/routes/account_details.js
- app/styles/_search.scss
- app/templates/account_details.hbs
- app/templates/authenticate.hbs
- app/templates/login.hbs
- app/templates/search_organisation.hbs
Hi Team,
This is PR for New User sign up features some bugs pointed in comments on JIRA ticket GCW-2132.
https://jira.crossroads.org.hk/browse/GCW-2132?focusedCommentId=31644&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-31644.
I have added those fixes. Please review it and let me know if any change is required.
Thanks
> GCW-2132-Infinity-loader bug on changing search text.

- app/controllers/item.js
- app/templates/item.hbs
- package.json
- tests/acceptance/browse-test.js
- yarn.lock
Hi Team,
This is Fix for the Inventory number display issue in logged out state.
https://jira.crossroads.org.hk/browse/GCW-2153?focusedCommentId=31806&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-31806.
Please review the PR and let me know if any change is required.
Thanks.
> Fixed: Inventory Number display issue on Logged out state.

- app/controllers/application.js
- app/services/cart.js
Hi Team,
This PR fixes issue of item not able to remove from cart.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2181
Please review and let me know if any other changes are required.
Thanks.
> GCW-2181 Cannot remove item from cart fix

- app/controllers/item.js
- app/controllers/package.js
Hi Team,
This PR fixes issue of item not getting removed from ember data after being designated
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2194
Please let me know if any other changes are required. 
Thanks
> GCW-2194 Remove item from ember-data

- app/controllers/order/transport_details.js
- app/models/order.js
Adding an api call to save the address ID to the order, and bits of refactoring :)
Dependant on https://github.com/crossroads/api.goodcity/pull/569, please review this first :)
> GCW 2014 Save address to order 

- app/styles/_cart_sidebar.scss
- app/templates/cart_content/_full_view.hbs
- app/templates/cart_content/_items.hbs
Hi Team,
This PR add feature of redirecting to item detail page on clicking on item in cart.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2196
Please review it and let me know if further changes are required.
Thanks
> GCW-2196 Clicking on cart item should redirect to item detail page

- app/components/add-request.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/account_details.hbs
- app/templates/login.hbs
- app/templates/order/appointment_details.hbs
- app/templates/order/booking_success.hbs
- app/templates/order/client_information.hbs
- app/templates/order/confirm_booking.hbs
- app/templates/order/goods_details.hbs
- app/templates/order/search_code.hbs
- app/templates/request/hk_identity_type_details.hbs
- app/templates/request/rbcl_identity_type_details.hbs
- app/templates/request_purpose.hbs
Hi Team,
This PR contains translations and text changes suggested on ticket GCW-2145.
Please review and let me know in case of any changes.
Thanks.
> add translations for booking

- app/styles/components/_add-request.scss
- app/templates/order/appointment_details.hbs
- app/templates/order/client_information.hbs
- app/templates/order/confirm_booking.hbs
- app/templates/order/goods_details.hbs
- app/templates/order/search_code.hbs
- app/templates/request_purpose.hbs
Hi team,
This PR contains the Changes for large screen display of booking-appointment feature.
> [GCW-2145] - css changes for book-appointment

- app/controllers/order/client_information.js
- app/styles/_request_purpose.scss
- app/templates/order/booking_success.hbs
Hi team this PR fixes the UI related issues for small medium and large screens for the last page.
> [GCW-2145]-Fix CSS for last page(success page)

- app/controllers/item.js
- config/environment.js
- cordova/config.xml
- package.json
Hi Team,
This is PR for GCW-2165- Android Deeplinking.
Please review this PR and let me know if any change is required.
Thanks.
> Gcw 2165 - Adding Deep linking for browse stock app

- .circleci/config.yml
- ember-cli-build.js
Hi Team,
This PR has following features:-
- Adds fingerprinting to JS files
- Uploads source map to rollbar
Jira tickets:- https://jira.crossroads.org.hk/browse/GCW-2214
Please review it and let me know if any changes are required. 
Thanks
> GCW-2214 Fingerprinting turned on and sourcemap upload

- app/controllers/application.js
- app/controllers/package.js
- app/styles/_cart_sidebar.scss
- app/templates/cart_content/_full_view.hbs
- app/templates/cart_content/_items.hbs
Hello Team, 
This PR fixes the issue of Clicking item details in cart resulted in null queryParams, Please review and comment if any changes are needed.
**JIRA link:** https://jira.crossroads.org.hk/browse/GCW-2196
Thanks
> [GCW-2196] clicking on item in cart fix

- app/controllers/application.js
Hello team, 
In previous fix, i was facing some issue, i.e. once the cart is hidden, i had to click the show card icon twice, Now this is fixed.
Thanks
> [GCW-2196] - Minor fix in cart toggling

- app/locales/en/translations.js
Hi team this PR fixes the issue of Login Popup spelling mistake.
Please review and comment 
Thanks.
> Fix Spelling Error On login Popup

- config/environment.js
Hi team, this PR will fix the issue of not rendering the proper app version in mobile app.
Thanks
> [GCW-2209] - Show App Version

- .circleci/config.yml
- app/controllers/home.js
- app/styles/app.scss
- app/templates/home.hbs
- package.json
- yarn.lock
Reverts crossroads/browse.goodcity#250
> Revert "Floating arrow for scrolling to bottom"

- app/locales/zh/translations.js
Hi Team , 
This PR fixes following issue: 
Thanks.
> missing translation issue on sms pin screen

- app/routes/order/confirm.js
- app/templates/account_details.hbs
- app/templates/application.hbs
- app/templates/order/appointment_details.hbs
- app/templates/order/booking_success.hbs
- app/templates/order/client_information.hbs
- app/templates/order/confirm_booking.hbs
- app/templates/order/goods_details.hbs
- app/templates/request_purpose.hbs
Hello team, please review this PR for UI-display for large screen fix.
Thanks.
> Fix css issues in book appointment large screens

- app/controllers/order/goods_details.js
- app/styles/_request_purpose.scss
- app/templates/order/goods_details.hbs
Hello Team, this PR will fix the issue for No Good request submission issue on goods_details page.
=> require user to request at least one thing 
> GCW-2145 Require user to request at least one thing for book-appointment

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/order/goods_details.hbs
Hi team, this PR is for fixing one issue reported by @steveyken in the message, and also moving that text to translations file. Please review.
> [GCW-2145] Move text to translation file

- app/templates/components/add-request.hbs
- app/templates/components/book-appointment.hbs
- app/templates/order/appointment_details.hbs
- app/templates/order/client_information.hbs
- app/templates/order/goods_details.hbs
- app/templates/request/hk_identity_type_details.hbs
- app/templates/request/rbcl_identity_type_details.hbs
- app/templates/request_purpose.hbs
- tests/acceptance/book-appointment-test.js
Hello Team, 
This PR is for book appointment feature acceptance test cases for all pages.
Thanks
> Gcw 2145 Acceptance Test cases for Book Appointment feature

- config/environment.js
Hi team, this PR will show the correct app versions on the application.
Please review and comment
Thanks.
> [GCW-2209] Show app version

- app/controllers/application.js
- app/templates/sidebar.hbs
Hi team, while testing, found out, app version was displayed on web app also, so made some changes to hide it from web. Please review and comment.
Thanks.
> GCW-2209 Hide app version from web app

- app/controllers/application.js
Hi team, this PR fixes the login and logout toggle for browse, please review.
Thanks.
> GCW-2250 fix login logout toggle

- app/components/message-box.js
- app/controllers/my_orders.js
- app/controllers/order/appointment_details.js
- app/controllers/order/client_information.js
- app/controllers/request_purpose.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/order.js
- app/routes/order/appointment_details.js
- app/routes/order/client_information.js
- app/routes/request_purpose.js
- app/styles/_my_orders.scss
- app/templates/my_orders.hbs
- app/templates/order/appointment_details.hbs
- app/templates/order/client_information.hbs
- app/templates/order/summary_tabs/booking.hbs
- app/templates/request_purpose.hbs
Hi Team,
This PR adds feature of modification and cancel of Order.
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-2243
Please review it and let me know if further changes are required.
Thanks
> GCW 2243 modify cancel order

- app/styles/_request_purpose.scss
- app/templates/order/appointment_details.hbs
- app/templates/order/booking_success.hbs
- app/templates/order/client_information.hbs
- app/templates/order/confirm_booking.hbs
- app/templates/order/goods_details.hbs
- app/templates/request_purpose.hbs
Hi team, 
This PR is for mobile UI fixes for booking appointment, Please review and comment.
Some of the UI screenshots
> GCW-2234 Fix mobile UI issues

- app/controllers/order/confirm_booking.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/beneficiary.js
- app/models/order.js
- app/models/user.js
- app/styles/app.scss
- app/styles/confirm_booking.scss
- app/styles/scroll_icon_settings.scss
- app/templates/order/_appointment_detail.hbs
- app/templates/order/_client_info_detail.hbs
- app/templates/order/_goods_detail.hbs
- app/templates/order/_request_purpose_detail.hbs
- app/templates/order/_user_details.hbs
- app/templates/order/confirm_booking.hbs
- tests/acceptance/cart-test.js
- tests/unit/models/order-test.js
- tests/unit/models/user-test.js
Hi Team,
This PR adds order confirmation detail.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2244
Please review and let me know if any changes are required.
Thanks
> GCW-2244 Order confirmation screen

- app/locales/zh/translations.js
Hi team, 
The PR updates the chinese translations for district field, provided by Nokia.
Thanks.
> Add tranlations for district field in request purpose page

- app/controllers/order/transport_details.js
- app/models/booking_type.js
Hi Team,
This PR contains changes to assign `online-order` booking type for order submission from cart.
Please review.
Thanks.
> assign booking type to online order

- app/controllers/order/transport_details.js
- app/controllers/order_details.js
- app/controllers/request_purpose.js
- app/models/order.js
- app/models/purpose.js
- app/routes/request_purpose.js
Hi Team,
This PR is to handle draft order scenario.
https://jira.crossroads.org.hk/browse/GCW-2247
Please review.
Thanks.
> Gcw 2247 fix appointment draft orders

- app/controllers/request_purpose.js
Hi Team,
This PR fixes request purpose edit bug
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2287
Please review
> GCW-2287 Request purpose edit bug

- app/components/book-appointment.js
- app/controllers/my_orders.js
- app/controllers/order/appointment_details.js
- app/controllers/order/client_information.js
- app/controllers/order/confirm_booking.js
- app/controllers/order/goods_details.js
- app/controllers/request_purpose.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/mixins/cancel_order.js
- app/models/order.js
- app/styles/_my_orders.scss
- app/templates/my_orders.hbs
- app/templates/order/_cancel_order.hbs
- app/templates/order/_cancel_order_button.hbs
- app/templates/order/_ggv_form.hbs
- app/templates/order/_self_vehicle_form.hbs
- app/templates/order/appointment_details.hbs
- app/templates/order/client_information.hbs
- app/templates/order/confirm.hbs
- app/templates/order/confirm_booking.hbs
- app/templates/order/goods_details.hbs
- app/templates/request_purpose.hbs
- tests/acceptance/cancel-booking-test.js
Hi Team,
This PR adds Order cancellation feature for Order.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2285
Please review and let me know if further changes are required.
Thanks
> GCW-2285 cancel booking

- app/controllers/application.js
- app/templates/application.hbs
Hi Team,
This PR fixes sidebar issue.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2229
Please review, thanks.
> GCW-2288 sidebar fix

- app/controllers/order/search_code.js
- app/models/package_type.js
Hi Team,
This PR adds sync of allow_requests of code to package_type of gc
Please review
Thanks
> GCW-2239 allow request sync

- app/controllers/my_orders.js
- app/routes/my_orders.js
- app/styles/templates/_application.scss
- app/styles/templates/_package_category.scss
- app/templates/my_orders.hbs
- app/templates/package_category.hbs
- app/templates/sidebar.hbs
This PR addresses the following tickets -> 
* GCW-2292
* GCW-2207
* GCW-2204
> Small layout fixes

- app/models/booking_type.js
- app/models/order.js
- app/routes/order/appointment_details.js
- app/routes/order_details.js
- app/routes/request_purpose.js
- app/templates/my_orders.hbs
- app/templates/order/_order_block.hbs
- app/templates/order/_order_header.hbs
- tests/acceptance/my_orders-test.js
Hi Team,
This PR contains changes for edit orders from my orders page with association changes.
Please review.
Thanks.
> Gcw 2288 user resumes submission of existing draft

- app/controllers/application.js
- app/templates/application.hbs
Hi Team,
This PR fixes sidebar and cart-sidebar issue for mobilescreen.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2303
Please review
> GCW-2303 Sidebar fix

- app/controllers/order/client_information.js
Hi Team,
This PR includes bug fixes for GCW-2243
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2243
Please review
> GCW-2243 Bug bug fixes

- app/components/select-appointment-date.js
- app/routes/order/appointment_details.js
Hi Team,
This PR contains changes to keep timeselection when user clicks on back button from submit page.
Please review.
Thanks.
> keep appointment time selection on back button

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/order/_user_details.hbs
Hi Team,
This PR adds some minor fixes for feature: Browse - implement confirmation screen for booking
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2244
Please review.
> GCW-2244 Minor fixes

- Rakefile
- app/locales/en/translations.js
- app/locales/zh/translations.js
- cordova/config.xml
- tests/acceptance/browse-test.js
Hi Team,
This PR contains changes for changing app name from `Browse` to `GoodCity for Charities`. 
Thanks.
> change app name and title on browse page

- Rakefile
- app/locales/en/translations.js
- app/locales/zh/translations.js
- cordova/config.xml
- tests/acceptance/browse-test.js
Reverts crossroads/browse.goodcity#297
> Revert "change app name and title on browse page"

- app/controllers/order/confirm_booking.js
- app/controllers/request_purpose.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/authorize.js
- app/routes/post_login.js
- app/routes/request_purpose.js
- app/services/cart.js
- app/services/session.js
- app/styles/templates/_schedule_details.scss
- app/templates/order/_schedule_summary.hbs
- app/templates/order/schedule_details.hbs
- app/templates/request_purpose.hbs
Note: will merge this for Matt to test
> New order flow : set items from cart properly

- app/controllers/request_purpose.js
- package.json
Hi Team,
This PR fixes issue mentioned on a ticket: https://jira.crossroads.org.hk/browse/GCW-2411
Please review.
Thanks.
> #Feb2019Release1

- app/controllers/order/client_information.js
- app/controllers/order/schedule_details.js
- app/controllers/request_purpose.js
Hi Team,
This PR fixes issue with routing for editing an item from the booking tab and clicking on the save changes button.
Please review.
Thanks.
> Gcw 2404 change routing for my orders page

- app/components/variable-height-textarea.js
- app/controllers/orders/conversation.js
- app/routes/orders/conversation.js
Hi team this PR is for Chat scrollHeight bug fix
https://rollbar.com/crossroads_it/browse.goodcity/items/412/
> GCW-2425 fix minor issues for scrollHeight

- app/controllers/orders/detail.js
- app/controllers/orders/goods.js
- app/models/order.js
- app/styles/_messages.scss
- app/styles/templates/_application.scss
- app/templates/orders/_order_tabs.hbs
- tests/acceptance/my_orders-test.js
Hi Team this PR fixes the UI issue for tabs
> GCW-2425 remove redundant code fix browse chat tab UI

- app/controllers/order/client_information.js
- app/controllers/order/schedule_details.js
- app/controllers/orders/detail.js
- app/controllers/request_purpose.js
- app/routes/order/client_information.js
- app/routes/order/schedule_details.js
- app/templates/order/_order_block.hbs
- app/templates/order/client_information.hbs
- app/templates/order/schedule_details.hbs
- app/templates/request_purpose.hbs
Hi Team,
This PR retains transition for order edit.
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-2375
Please review.
thanks.
> GCW-2375 retain transition

- app/components/variable-height-textarea.js
- app/controllers/orders/conversation.js
- app/helpers/apply-line-break.js
- app/styles/_messages.scss
- app/styles/_my_orders.scss
- app/templates/orders/_message_template.hbs
- app/templates/orders/_order_tabs.hbs
Hello Team, 
This PR fixes UI issues on browse app for messaging.
Thanks
> GCW-2415 fix UI for browse messaging

- app/controllers/order/client_information.js
- app/styles/_my_orders.scss
- app/styles/templates/_application.scss
- app/styles/templates/_client_information.scss
- app/templates/order/client_information.hbs
- app/templates/order/schedule_details.hbs
- app/templates/orders/_order_tabs.hbs
Hi Team,
This PR is regarding spinner loading twice on saving client information. PR also includes responsiveness issue on radio button label on client information and Transport details page.
Please review the PR and let me know if any change is required.
Thanks
> GCW-2422- Spinner showing twice fix

- app/controllers/request_purpose.js
Hi Team,
This PR sorts districts alphabetically.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2439
Please review
> GCW:2439 Sorted district selection

- app/components/validate-appointment.js
- app/templates/order/schedule_details.hbs
Hi Team,
This PR removed validation for `Discard changes` button click.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2381
Please review
> GCW:2381 Discard button validation removed

- app/components/variable-height-textarea.js
- app/controllers/subscription.js
- app/styles/_messages.scss
- app/templates/orders/_message_template.hbs
Hi team 
this PR contains changes for minor fixes in chat
- restrict blank message
thanks
> GCW-2425 Fixing issues for chat

- app/controllers/orders/conversation.js
- app/controllers/orders/detail.js
- app/controllers/subscription.js
- app/models/order.js
- app/routes/orders/conversation.js
- app/services/messages.js
- app/styles/_cart_sidebar.scss
- app/styles/_messages.scss
- app/styles/_my_orders.scss
- app/styles/_order_block.scss
- app/templates/_cart_truck_icon.hbs
- app/templates/order/_order_block.hbs
- app/templates/orders/_order_tabs.hbs
- app/templates/orders/unread_message_bubble.hbs
Hi team, this PR is for marking unread messages to read. 
Please review
Thanks
> GCW-2414 read unread tracking of messages

- app/controllers/account_details.js
Add query param in request purpose page, if its bookingtype and transitioning to request purpose.
> Fix minor issue faced in book appointment

- app/styles/confirm_booking.scss
- app/templates/order/_orders_package_detail.hbs
- app/templates/order/confirm_booking.hbs
Hi Team,
This PR is for JIRA ticket GCW-2422- Showing online orders on Confirmation page. I have added the online orders package block. Please review the PR and let me know if any change is required.
Thanks.
> GCW-2422-Add online orders goods on confirm page

- app/models/order.js
Hi Team, 
This PR is for JIRA ticket GCW-2417 (https://jira.crossroads.org.hk/browse/GCW-2417). PR include fix for not reflecting change from order Transport page on Confirm booking page.
Please review the PR and let me know if any change is required. 
Thanks.
Changes:
https://github.com/crossroads/browse.goodcity/pull/332/files#diff-5e05cf1b474483dc6d417bca3f1b8a92R115
https://github.com/crossroads/browse.goodcity/pull/332/files#diff-5e05cf1b474483dc6d417bca3f1b8a92R115
https://github.com/crossroads/browse.goodcity/pull/332/files#diff-5e05cf1b474483dc6d417bca3f1b8a92R133
> GCW-2417- Transport Details change not reflected on confirm page on changing.

- yarn.lock
Hello team 
Please review this. This contains the latest upgraded cordova-lib which includes organisation search changes.
Thanks
> GCW-2487 organisation search improvements

- .circleci/config.yml
- Rakefile
- app/index.html
- app/locales/en/translations.js
- app/locales/zh/translations.js
- cordova/config.xml
- package.json
- tests/acceptance/browse-test.js
- tests/index.html
Hi Team,
This PR fixes changes name of Browse app to publish on iTunes
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2305
Please review
Thanks
> GCW 2305 app name change

- app/controllers/application.js
Hi Team,
This PR fixes issue or item redirection from cart
Please review.
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-2499
Thanks
> GCW-2499 Redirect item in cart issue

- app/models/order.js
This PR fixes the issues mentioned on GCW-2422 regarding items details invisible on confirmation screen. Please review
> GCW-2422 fix item details not visible

- app/controllers/orders/conversation.js
- app/controllers/subscription.js
- app/models/message.js
- yarn.lock
Hi team 
This PR fixes the issue of first message issue mentioned in the link below, also this PR contains the changes for removal of sender model.
https://jira.crossroads.org.hk/browse/GCW-2425?focusedCommentId=33313&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33313
Thanks
> GCW-2425 fix chat issues

- app/controllers/account_details.js
- app/controllers/authenticate.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/organisations_user.js
- app/models/user.js
- app/routes/login.js
- app/styles/templates/_login.scss
- app/templates/account_details.hbs
- app/templates/login.hbs
- tests/acceptance/account_details-test.js
- tests/factories/organisations_user.js
Hi Team,
This PR contains changes to enable sign-up and login using email on browse app.
Please review.
Thanks.
> Gcw 2432 sign up with email

- app/components/focus-textfield.js
- app/controllers/order/search_code.js
- app/routes/order/confirm_booking.js
- app/routes/order/schedule_details.js
- app/styles/account_details.scss
- app/styles/confirm_booking.scss
- app/templates/account_details.hbs
- app/templates/order/booking_success.hbs
Hi Team,
This PR is for responsive validation UI fixes. Along with fixes mentioned on ticket GCW-2363 comments. https://jira.crossroads.org.hk/browse/GCW-2363?focusedCommentId=33653&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-33653
Please review the PR and let me know if any change is required. 
Thanks
> Account details validation UI fixes

- app/components/book-appointment.js
- app/controllers/account_details.js
- app/controllers/application.js
- tests/acceptance/cart-test.js
Hi team,
This PR makes user to fill account details form if his account details are incomplete.
Please review.
Thanks
> GCW-2459 account-details-form-on-online-order

- app/controllers/request_purpose.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/order/client_information.hbs
If you are editing an order, edit request purpose save changes.
Go to home click on book appointment
We were not able to go ahead for fresh appointment.
This PR fixes that issue. Please review.
Change => 
https://github.com/crossroads/browse.goodcity/pull/342/files#diff-33c6583207659f5e73bc65f4ef39806cR122
> fix request purpose

- app/templates/account_details.hbs
Hello Team this PR addresses this issue
https://jira.crossroads.org.hk/browse/GCW-2459?focusedCommentId=33673&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33673
Please review. 
Thanks
> Fix back link on account details

- app/controllers/authenticate.js
- app/models/user.js
- app/styles/account_details.scss
- app/templates/account_details.hbs
- tests/acceptance/account_details-test.js
Hi Team, 
This PR introduces the verified flag for email and mobile.
Please review.
Thanks
> GCW-2479 show verified flag for email and mobile

- app/controllers/authenticate.js
- app/templates/login.hbs
This PR adds 4,7,8 to the regex for mobile validations.
> GCW-2517 add 4,7,8 in the regex for mobile

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/router.js
- app/routes/my_account.js
- app/routes/my_dashboard.js
- app/routes/my_orders.js
- app/routes/my_updates.js
- app/styles/_my_account.scss
- app/styles/_my_dashboard.scss
- app/styles/_my_orders.scss
- app/styles/app.scss
- app/templates/my_account.hbs
- app/templates/my_dashboard/_my_dashboard_tabs.hbs
- app/templates/my_orders.hbs
- app/templates/my_updates.hbs
- app/templates/sidebar.hbs
- tests/acceptance/my-dashboard-test.js
- tests/acceptance/my_orders-test.js
Hi team this PR is for my dashboard screen
Thanks.
> GCW 2467 my dashboard

- app/controllers/account_details.js
- app/models/organisations_user.js
- app/templates/account_details.hbs
Hi Team,
This PR fixes issue: 
- If we sign up using email id and then enter mobile number on accounts details page then it do not saves it in db.
- PreferredContactNumber field was not considered while checking for account details are complete or not.
Please review.
Thanks.
> fix issue: mobile number not getting saved to db on email sign up

- app/controllers/package_category.js
Hi Team,
This PR is for JIRA ticket GCW-2047- changing page does reset page back to top(https://jira.crossroads.org.hk/browse/GCW-2047). Issue is fixed. 
Please review the PR and let me know if any change is required.
Thanks.
> GCW-2047-changing pages does not reset the page back to the top

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/user.js
- app/templates/order/_user_details.hbs
Hi Team,
This PR adds preferred_contact_number to order confirmation page.
Please review.
Thanks.
> add preferred contact number to confirmation page

- app/controllers/account_details.js
Hi Team,
FIxes issue: Email not getting saved to db if we sign up using mobile number.
Please review.
Thanks.
> email is not getting saved to db when we sign up using mobile number

- app/controllers/order/goods_details.js
- app/models/order.js
Hi Team,
This PR is for goods not getting added on goods_details page during Booking Appointment. Also fix for ticket GCW-2528-client details not getting updated (https://jira.crossroads.org.hk/browse/GCW-2528). Please, review this PR and let me know if any change is required.
Thanks.
> FIX => Goods Details not getting created 

- app/controllers/application.js
- app/routes/orders/goods.js
- app/services/cart.js
When we come on the `goods` page from `my_orders` we don't have the packages already loaded (we don't load all dependencies at startup)
This code loads them if they are missing
> Fetch packages when missing

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/order/client_information.hbs
Hello team, 
This PR fixes an issue reported by Ambika for missing translation for client info page.
Please Review.
Thanks.
> Fix missing translation error

- app/router.js
- config/environment.js
- package.json
- yarn.lock
Hi Team,
This adds googles analytics for browse app.
https://jira.crossroads.org.hk/browse/GCW-2539
Please review.
Thanks.
> integrate google analytics

- app/router.js
- config/environment.js
- package.json
- yarn.lock
Hi Team,
This will add google analytics for browse site.
https://jira.crossroads.org.hk/browse/GCW-2539
Please review.
Thanks.
> Google analytics integration

- app/styles/_sidebar.scss
- app/styles/templates/_home.scss
- app/templates/home.hbs
Hello Team, 
This PR fixes the issues for the UI layout on larger screens.
Thanks
> GCW-2516 fix UI related issues for large screens

- app/styles/templates/_home.scss
- app/templates/home.hbs
Cart icon on home screen invisible, so this is a fix for that.
Please review.
Thanks.
> fix minor cart icon css issue found while testing

- app/controllers/account_details.js
- app/controllers/authenticate.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/models/organisations_user.js
- app/models/user.js
- app/routes/post_login.js
- app/styles/account_details.scss
- app/styles/templates/_home.scss
- app/styles/templates/_login.scss
- app/templates/account_details.hbs
- app/templates/authenticate.hbs
- app/templates/order/_user_details.hbs
- package.json
- tests/acceptance/account_details-test.js
Hi Team,
This PR contains fixes for:
- Email/mobile not getting saved to db on sign up.
- Add verified flag for email/mobile.
- Add preferred contact number.
- show mobile/email on pin screen.
Please review.
Thanks.
> #April2018Release3 : Email feature fixes

- app/controllers/order/client_information.js
- package.json
- yarn.lock
Hi Team,
This PR is fix for Client information not appearing on confirm booking page on first time creation.  Please review the PR and let me know if any change is required.
Thanks
> FIX=> Client information fix not appearing on online order creation

- app/components/select-appointment-date.js
Hello team, 
This PR fixes the extra space on the schedule-details page. which causes an issue on the mobile screens
Thanks
> Fix extra space beneath the schedule-details page

- app/templates/home.hbs
- package.json
Hi Team,
This PR removes image from home page for now as it looks scary. 😅 
We will add a new image soon.
Please review.
Thanks.
> #May2019Release2

- app/controllers/application.js
- app/styles/_sidebar.scss
- app/templates/application.hbs
- app/templates/sidebar.hbs
Hi Team,
This is fix for pushing sidebar menu below download banner. Please review the PR and let me know if any change is required. 
Thanks
> FIX=> Pushing sidebar below download banner

- app/controllers/account_details.js
- app/controllers/application.js
- app/styles/_sidebar.scss
- app/templates/application.hbs
- app/templates/sidebar.hbs
- package.json
Hi Team,
This PR contains changes for:
- Fix account details issue if a mobile number is blank.
- Fix app banner redirecting to ios app store.
Please review.
Thanks.
> #May2019Release3

- app/controllers/application.js
- app/templates/account_details.hbs
On clicking book appointment button from home page, content of account details shifts to right. 
This PR contains its fix.
Please review 
Thanks
> fix account details shifting to right 

- app/controllers/authenticate.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/post_login.js
- app/styles/templates/_login.scss
- app/templates/account_details.hbs
- app/templates/authenticate.hbs
- app/templates/login.hbs
- tests/acceptance/book-appointment-test.js
Hello team 
This PR fixes the login authenticate and account details forms.
Please review
Thanks.
> GCW-2586 forms perfected

- app/components/book-appointment.js
- app/controllers/account_details.js
- app/controllers/request_purpose.js
- app/templates/login.hbs
- app/templates/request_purpose.hbs
Please review this PR.
Ticket reference: https://jira.crossroads.org.hk/browse/GCW-2582
THanks
> GCW-2586 fix back link issues for request purpose

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/search_organisation.js
- app/styles/_search.scss
- app/templates/order/search_code.hbs
- app/templates/search_organisation.hbs
Hi Team,
This PR has changes related button and on clicking it redirects user back to account details form. And some minor CSS fix added. Please review the PR and let me know if any change is required. 
Thanks
> GCW-2586-Organisation selection issue from Account Details page

- app/styles/_request_purpose.scss
- app/templates/request_purpose.hbs
PR contains fix for this https://jira.crossroads.org.hk/browse/GCW-2608.
Please review.
> GCW-2608 back and cancel link no clickable

- app/styles/_search.scss
- app/templates/about.hbs
- app/templates/faq.hbs
- app/templates/order/search_code.hbs
- app/templates/privacy.hbs
- app/templates/terms.hbs
change class name to avoid application of global css.
> fix back button css

- app/styles/account_details.scss
- app/templates/account_details.hbs
This PR fixes minor layout issue for small screens.
Please review
> fix minor css issues for verified icon

- app/routes/application.js
Hi Team,
This PR contains fix for 'Something went wrong' error on Microsoft Edge on login on 'My Orders' page. Please review the PR and let me know if any change is required.
Thanks
> GCW-2385- 'Something went wrong' error message appears when logging in via 'My Orders'.

- app/controllers/order/schedule_details.js
There's a lot of prettier going on, but the only things that have been changed are Lines 53-57
Removed:
```javascript
if (date.isClosed) {
continue;
}
```
Changed: 
```javascript
let slots = date.slots.filter(s => !s.isClosed);
// becomes
let slots = date.slots;
```
> Ensure we show slots for orders even if slot is taken

- app/controllers/order/schedule_details.js
- package.json
Removed:
```javascript
if (date.isClosed) {
continue;
}
```
Changed: 
```javascript
let slots = date.slots.filter(s => !s.isClosed);
// becomes
let slots = date.slots;
```
> MayRelease - Fix time slots for online orders

- app/controllers/request_purpose.js
Hi Team,
This is fix for confirmation page not getting updated on adding items to cart. Please review the PR and let me know if any change is required. 
Thanks
> FIX=> GCW-2595- Confirmation page not getting updated on adding items to cart

- app/routes/search_organisation.js
Hi Team,
This PR is for ticket GCW-2620 (https://jira.crossroads.org.hk/browse/GCW-2620). Please review the PR and let me know if any change is required. Thanks
> FIX=> GCW-2620- Sidemenu getting dissappears on going back to 2 previous pages using browser back button

- app/controllers/application.js
- app/services/screenresize.js
- app/templates/application.hbs
Looks like my previous fix was too hopeful, they hbs and jquery are too intertwined it's hard not to break things :/
> Fix broken sidebar (whoopsie)

- app/locales/en/translations.js
- app/styles/templates/_login.scss
- app/templates/authenticate.hbs
- app/templates/login.hbs
Hello team, this PR Fixes the issues mentioned in this comment, except the last one. Created a separate ticket for that one.
https://jira.crossroads.org.hk/browse/GCW-2586?focusedCommentId=34388&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-34388
Thanks
> GCW-2586 fix issues mentioned by xceptionals

- app/controllers/application.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/browse.js
- app/styles/_sidebar.scss
- app/styles/templates/_browse.scss
- app/styles/templates/_package_category.scss
- app/templates/browse.hbs
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/components/paginated-items.hbs
- app/templates/package_category.hbs
- app/templates/sidebar.hbs
- tests/acceptance/browse-test.js
Hello Team this PR is for adding breadcrumbs on browse. 
Please review thanks.
> GCW-2617  breadcrumbs for browse

- app/controllers/item.js
- app/styles/templates/_item.scss
- app/styles/templates/_package_category.scss
- app/templates/item.hbs
- app/templates/package_category.hbs
This PR fixes the issues reported by Tim on GCW-2617.
Please review thanks.
> Gcw 2617 fix reported issues

- app/controllers/application.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/browse.hbs
- app/templates/package_category.hbs
- app/templates/sidebar.hbs
hello team, this PR is to hide search icon from live app until search feature is available, please review
> hide search icon from live until search feature is available

- app/controllers/application.js
- app/controllers/order/schedule_details.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/browse.hbs
- app/templates/package_category.hbs
- app/templates/sidebar.hbs
- package.json
Hello team, 
This PR adds changes to hide the search icon and add minor translations to browse app.
Hiding search icon for some time until the search feature is available.
Thanks
> #June Release2 

- app/adapters/application.js
- app/controllers/search_goods.js
- app/routes/home.js
- app/styles/_ellipsis.scss
- app/styles/_search.scss
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/item.hbs
- app/templates/search_goods.hbs
This PR is for sending the client to fetch pacakages from packages_controller instead of browse_controller.
Thanks
> GCW-2659 send client to packages_controller end_point instead of browse_controller

- app/adapters/application.js
- app/controllers/application.js
- app/controllers/search_goods.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/router.js
- app/routes/home.js
- app/routes/search_goods.js
- app/styles/_ellipsis.scss
- app/styles/_search.scss
- app/styles/templates/_login.scss
- app/styles/templates/_package_category.scss
- app/templates/browse.hbs
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/components/paginated-items.hbs
- app/templates/item.hbs
- app/templates/package_category.hbs
- app/templates/search_goods.hbs
- app/templates/sidebar.hbs
- package.json
- yarn.lock
Hello @team,
This PR adds the ability to search items on browse app.
Please review this PR.
Thanks.
> GCW 2616 browse goods search

- app/styles/_search.scss
- app/styles/_sidebar.scss
- package.json
- yarn.lock
As titled, this refers to ticket : https://jira.crossroads.org.hk/browse/GCW-2566
It includes some slight CSS changes.
@patrixr also modified the `package.json` scripts to support windows (using a cross-env package)
> Fix IE11 issues on search pages

- app/adapters/application.js
- app/controllers/application.js
- app/controllers/order/schedule_details.js
- app/controllers/search_goods.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/router.js
- app/routes/application.js
- app/routes/authorize.js
- app/routes/search_goods.js
- app/styles/_ellipsis.scss
- app/styles/_search.scss
- app/styles/_sidebar.scss
- app/styles/templates/_item.scss
- app/styles/templates/_login.scss
- app/styles/templates/_package_category.scss
- app/templates/browse.hbs
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/components/paginated-items.hbs
- app/templates/item.hbs
- app/templates/package_category.hbs
- app/templates/request/hk_identity_type_details.hbs
- app/templates/request/rbcl_identity_type_details.hbs
- app/templates/search_goods.hbs
- app/templates/sidebar.hbs
- package.json
- yarn.lock
Hi Team,
This PR contains changes:
- Redirect the user to login page instead of showing modal.
- Browse goods search.(GCW-2616) 
- Fix IE11 issues on search pages. (GCW-2566)
- Fix:  cross icon on image is not clickable on ios safari. (GCW-2676)
- Hide unwanted scrollbars. 
- Search UI fixes.
Please review.
Thanks.
> #July2019Release1

- app/components/app-canvas.js
- app/controllers/application.js
Details: https://jira.crossroads.org.hk/browse/GCW-2616
> Fix sidebar bug - GCW-2616

- app/adapters/application.js
- app/controllers/application.js
- app/controllers/search_goods.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/router.js
- app/routes/application.js
- app/routes/authorize.js
- app/routes/search_goods.js
- app/styles/_ellipsis.scss
- app/styles/_search.scss
- app/styles/_sidebar.scss
- app/styles/templates/_item.scss
- app/styles/templates/_login.scss
- app/styles/templates/_package_category.scss
- app/templates/browse.hbs
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/components/paginated-items.hbs
- app/templates/item.hbs
- app/templates/package_category.hbs
- app/templates/request/hk_identity_type_details.hbs
- app/templates/request/rbcl_identity_type_details.hbs
- app/templates/search_goods.hbs
- app/templates/sidebar.hbs
- package.json
- yarn.lock
Reverts crossroads/browse.goodcity#417
> Revert "Revert "#July2019Release1""

- app/styles/_sidebar.scss
- app/styles/templates/_home.scss
- app/templates/home.hbs
https://jira.crossroads.org.hk/browse/GCW-2639
> Fix background being squished on homepage

- yarn.lock
Reverts crossroads/browse.goodcity#427
> Revert "commit yarn file"

- app/services/api-base-service.js
This PR sets session language while submitting order
> set session language

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/application.js
This PR Extends from email story.
User if reaches a not allowed place, should be shown not allowed error.
and on click of ok, user should be redirected to home page.
Thanks
> Show not allowed error if 403, otherwise something went wrong

- bower.json
Fork commit link  -https://github.com/abhinav098/pickadate.js/commit/22fa976410286fae07c074b448723a0ca44a5ff6
Forked to crossroads - https://github.com/crossroads/pickadate.js/commits/master
> Fix automatic scroll on account details page.

- app/styles/_search.scss
- app/templates/search_goods.hbs
This PR fixes minor cursor issues, for search items. 
Please review thanks.
> Fix cursor issues

- app/controllers/submitted_order_selection.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/styles/_my_orders.scss
- app/styles/templates/_client_information.scss
- app/templates/submitted_order_selection.hbs
Hi Team,
This PR is for UI fixes for  GCW-2683- Adding items to submitted Orders. Please review it and let me know if any change is required.
Thanks
> Fix=> UI fix for GCW-2683- Adding items to submitted Orders

- app/styles/templates/_client_information.scss
> FIX=> css fix for radio button for medium and large screen

- app/components/small-cart-toggle-view.js
- app/controllers/application.js
- app/initializers/session.js
- app/routes/application.js
- app/services/cart.js
- app/styles/_cart_sidebar.scss
- app/styles/_sidebar.scss
- app/templates/cart_content/_full_view.hbs
- app/templates/cart_content/_items.hbs
- app/templates/cart_details_sidebar.hbs
- app/templates/components/small-cart-toggle-view.hbs
- app/templates/login.hbs
- app/templates/order/client_information.hbs
- app/templates/order/schedule_details.hbs
- app/templates/request_purpose.hbs
Changes:
- Add `Show order summary` widget back into the order process
- Fix the cart item list within the widget
- Fix issue where clicking on `show` on the car sidebar right after requesting an item would close the sidebar instead of expanding it.
> Fixes : cart widget + cart sidebar

- app/controllers/item.js
- app/controllers/package_category.js
- app/routes/package_category.js
- app/templates/_breadcrumbs.hbs
This PR fixes the category issue that Patrick reported. 
https://jira.crossroads.org.hk/browse/GCW-2738
> Fix category selection issue

- app/controllers/submitted_order_selection.js
- app/routes/submitted_order_selection.js
- app/styles/templates/_client_information.scss
- app/templates/submitted_order_selection.hbs
Hi Team,
This PR is fix for issue on Order Selection page. When user changes Order state from "Processing" to "Awaiting Dispatch" in Stock App. This does not update Order Selection page where cart items are merged with existing Orders.
Please review the PR and let me know if any change is required.
Thanks.
> GCW-GCW-2728- Order state change do not update order selection page.

- app/controllers/order/goods_details.js
It disables continue button if no request added to appointment.
> disable continue button if no requests

- app/routes/home.js
This issue is reference to ticket no. : https://jira.crossroads.org.hk/browse/GCW-2593
> Fix text on top of browse app for small devices

- app/routes/application.js
Render error messages coming from the API.
> GCW-2763 Handle errors graciously

- app/styles/_search.scss
- app/styles/templates/_package_category.scss
Hi team,
This PR contains Css changes for upgrading font-awesome from 4 to 5.
Please review.
Thanks.
> Gcw 2298 fontawesome update to version 5 browse app

- app/services/logger.js
Hello team, 
This PR fixes a rollbar issue which was observed on 17th Sept,2019.
Rollbar link: https://rollbar.com/crossroads_it/browse.goodcity/items/612/
Please review 
Thanks.
> fix rollbar #612

- package.json
Hi Team,
This PR increments the app version.
Please review.
> app version upgraded

- app/routes/application.js
- app/templates/orders/goods.hbs
Hi Team,
This PR contains changes for review suggestions added on PR: https://github.com/crossroads/browse.goodcity/pull/459
Please review.
Thanks.
> review fixes for September2019Release1 PR

- app/styles/_sidebar.scss
This issue is reference to ticket no.  https://jira.crossroads.org.hk/browse/GCW-2562 which is fixed now.
> Fix siderbar-menu options when browser height changes

- .circleci/config.yml
https://jira.crossroads.org.hk/browse/GCW-2809
It adds new p12 and provisioning profiles for production. 
Please review.
Thanks.
> GCW-2809 add new p12 and provisioning profile

- app/controllers/account_details.js
BUG: Fixes error displaying on user creation from browse app.
account_detail form on browse app
> GCW-2838 fix user creation error handling

- app/services/logger.js
BUG:  data is not defined error on rollbar.
NOTE: This PR fixes the rollbar issue.  Rollbar is not catching actual errors as  As data variable is undefined. 
https://rollbar.com/crossroads_it/browse.goodcity/items/615/
Please Review.
Thanks.
> fix rollbar issue: data is not defined

- Rakefile
- package.json
Hi Team,
This PR includes:
- Fixed error handling for user creation. (i.e It will show a proper error instead of [object object])
- Fixed rollbar issue of data is undefined.
Please review.
Thanks.
> #November2019Release1

- app/components/faq-questions.js
- app/controllers/faq.js
- app/routes/static_pages.js
- app/styles/_static_pages.scss
- app/templates/components/faq-questions.hbs
- app/templates/faq.hbs
https://jira.crossroads.org.hk/browse/GCW-2888
BUG: This PR fixes scroll to question description feature on android and ios app.
/faq page on browse app.
Screenshots:
> Gcw 2888 the links on the fa qs page don work on mobiles

- app/models/package.js
- tests/unit/models/package-test.js
https://jira.crossroads.org.hk/browse/GCW-2062
This PR adds prefix to Length, width, hight values.
> Gcw 2062 browse design clearer dimensions ui

- app/styles/components/_add-request.scss
https://jira.crossroads.org.hk/browse/GCW-2912
This PR only makes the button area clickable instead of the surrounding area.
Please review.
> GCW-2912 only making button area click able

- Gemfile.lock
> FIX vulenrabilities

- config/environment.js
BUG: Rollbar environment was not being correctly sent
> Fixed Rollbar environment

- app/styles/templates/_home.scss
https://jira.crossroads.org.hk/browse/GCW-2896
What this PR do?
This PR adds position relative property to the parent element of the absolute child.
Screenshots:
Please review:
> GCW-2896 added position relative to parent of absolute children

- app/styles/templates/_client_information.scss
https://jira.crossroads.org.hk/browse/GCW-2912
The bug this PR fixes The 'Please indicate the type and quantity of each item needed. Etc...' text resizes depending on the width of the browser issue.
Please review.
> GCW-2912 on large device increse the font size of text

- app/controllers/order/client_information.js
- app/controllers/order/schedule_details.js
- app/templates/order/_order_summary.hbs
- app/templates/order/client_information.hbs
- app/templates/order/schedule_details.hbs
- app/templates/request_purpose.hbs
https://jira.crossroads.org.hk/browse/GCW-2953
Bugs:  This PR hides the order summy if the user clicks on the book appointment button to get a package.
Please review:
> hide order summary in case of book appointment

- app/styles/_search.scss
- app/templates/search_goods.hbs
https://jira.crossroads.org.hk/browse/GCW-2954
BUG: This PR makes the entire area of Done button clickable.
Please review
> made done button clickable on ipad and small screen device

- app/styles/_search.scss
https://jira.crossroads.org.hk/browse/GCW-2954
BUG: Specify bug 
This PR makes the done button on search widget clickable on the iPad.
Please review.
> GCW-2954 made done button clickable on ipad

- app/styles/_search.scss
https://jira.crossroads.org.hk/browse/GCW-2954
Bug: on certain width done/back button is not completely selectable so adjust the width of the done button and the width of the search input field.
Please review.
> GCW-2954 make e part of done button clickable

- .circleci/config.yml
- app/models/package.js
- app/templates/item.hbs
https://jira.crossroads.org.hk/browse/GCW-2984
BUG:
This PR hides the size field from the front end if anyone of the following length X width X height is not present as all three fields are required to fill.
before:
Please review:
> Gcw 2984 dimensions are shown as null

- package.json
Hi team
This PR contains increase the app version in package.json file to 0.7.5
Please review.
> updated the version in package.json file to 0.7.5

- package.json
Reverts crossroads/browse.goodcity#503
> Revert "updated the version in package.json file to 0.7.5"

- app/controllers/authenticate.js
https://jira.crossroads.org.hk/browse/GCW-3020
This PR adds the missing action to the order summary section on the login page.
Please review.
> GCW-3020 added the missing action and cart service

- app/controllers/authenticate.js
- app/templates/account_details.hbs
- package.json
A small release to fix a bug preventing social workers from signing up properly.
Fixes:
* Clicking on the offline cart next to the login form causes an error
* Account details email field is broken and prevents users from filling in their details
> #Release - Feb6 - Bug fixes

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/mixins/cancel_order.js
- app/models/cancellation_reason.js
- app/models/order.js
- app/services/order-service.js
- app/services/preload-service.js
- config/environment.js
https://jira.crossroads.org.hk/browse/GCW-2931
FEATURE: Cancelling order applies "Changed mind" as the reason.
My Dashboard > Go to submitted order > cancel order. 
https://github.com/crossroads/api.goodcity/pull/885
> GCW-2931-Request cancellation reason for orders

- app/routes/order/schedule_details.js
This is related to an urgent request from the staff to lock down only appointments during the Coronavirus outbreak.
It will give the API more control over the dates that it sends
We will probably fast track this to Prod asap
> Send the booking_type_id when fetching appointment quotas

- app/routes/order/schedule_details.js
- package.json
This is related to an urgent request from the staff to lock down only appointments during the Coronavirus outbreak.
It will give the API more control over the dates that it sends
> Release send booking type for appointment slots

- app/controllers/item.js
- app/models/package.js
- app/templates/item.hbs
https://jira.crossroads.org.hk/browse/GCW-2985
Instead of displaying the quantity of packages available in hand (excluding only dispatched packages), display the quantity of packages available in stock and not designated. (show available quantity)
item page
> GCW-2985 display package available quantity

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/home.hbs
https://jira.crossroads.org.hk/browse/GCW-3054
Adds an orange alert to indicate Crossroads' distribution center is closed until a particular date.
Home page
> Add COVID-19 alert message

- app/locales/en/translations.js
- app/locales/zh/translations.js
**March2020 Release#2**
This release contains the following changes: 
- GCW-3069 fix login validation failure due to leading and trailing whitespaces
> March2020 Release#2

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/styles/_about.scss
- app/templates/about.hbs
- app/templates/home.hbs
https://jira.crossroads.org.hk/browse/GCW-3055
FEATURE: Updates the text on the website to be clearer about COVID arrangements
- Header on home page
- Warning alerts split into 2 alerts on home page to be clearer.
- New preamble on About page
> Tweaks to text for COVID

- app/controllers/item.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/application.js
https://jira.crossroads.org.hk/browse/GCW-3070
This PR will fix bug in browser app when a particular item is viewed when it is not available in the inventory.
Steps to reproduce:
1. View a package in the browse app
2. Designate all the quantities for the same package
3. Refresh the page in the browse app, the page breaks
Browse > Category
> GCW-3070 fix for page breaking if package is not present

- app/services/cart.js
https://jira.crossroads.org.hk/browse/GCW-2997
Add loading screen at the request and remove the item.
> GCW-2997 add loading screen at request and remove item

- app/templates/request/hk_identity_type_details.hbs
- app/templates/request/rbcl_identity_type_details.hbs
https://jira.crossroads.org.hk/browse/GCW-2988
All the validation message appears together when continue button is clicked in client's information page in browse app.
> GCW-2988-Validation Message all appears together now

- app/controllers/item.js
https://jira.crossroads.org.hk/browse/GCW-2588
fixed item page and back-link when category-id not provided URL
> GCW-2588 fixed item page and back-link when category-id not provided url

- app/templates/request_purpose.hbs
- yarn.lock
https://jira.crossroads.org.hk/browse/GCW-2926
Allow users to enter number 1 or greater than 1 in people benfitting column
> GCW-2926-FIX-Numeric input added to the page

- app/templates/order/client_information.hbs
https://jira.crossroads.org.hk/browse/GCW-2401
Character limit was added to the first name and last name field in client information
> GCW-2401-Character limit added to first name and last name field

- app/controllers/order/schedule_details.js
We have a setting on goodcity called `booking_margin`. That margin prevents people from selecting a pickup date on the same day or the days immediatly after. Essentially giving time for the staff to prepare the order.
Currently we do a `slice(bookingMargin)` on the days available. But if the first few days are holidays then we're not actually cutting any business days out.
This PR fixes that, by applying the `slice` to business days only.
+ general refactoring of the method
> Online order booking margin fix

- app/templates/my_account.hbs
https://jira.crossroads.org.hk/browse/GCW-3009
Removed show summary button from my account page
> GCW-3009-Fixed issue of show summary button

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/templates/request_purpose.hbs
https://jira.crossroads.org.hk/browse/GCW-2926
Numeric input will now accept 0 and null values too
> GCW-2926 Changed the UI to accept positive numbers and null values and neglect negative numbers

- app/components/back-link.js
- app/controllers/browse.js
- app/controllers/my_orders.js
- app/controllers/request_purpose.js
- app/routes/browse.js
- app/routes/my_orders.js
- app/routes/order/goods_details.js
- app/routes/request_purpose.js
- app/routes/static_pages.js
- app/templates/about.hbs
- app/templates/browse.hbs
- app/templates/components/back_link.hbs
- app/templates/faq.hbs
- app/templates/privacy.hbs
- app/templates/terms.hbs
- config/environment.js
https://jira.crossroads.org.hk/browse/GCW-3084
Removed old code of tracking back route which is not working after upgrade of ember as those features are removed.
Added changes for back link to previous pages.
> GCW-3084 removed old previous-route related code changes and added new back-link component

- app/templates/request_purpose.hbs
https://jira.crossroads.org.hk/browse/GCW-2926
Entering 0 in the peopleHelped Column now does not  dissappear
> Fix for 0 not disappearing

- app/templates/login.hbs
https://jira.crossroads.org.hk/browse/GCW-2921
Fix Backlink issue in the login page
> GCW-2921-Issue fixed in backlink in login page

- package.json
- yarn.lock
> Fix Segmentation fault on MacOS Catalina

- app/components/book-appointment.js
- app/controllers/my_orders.js
- app/controllers/request_purpose.js
- app/controllers/submitted_order_selection.js
- app/routes/submitted_order_selection.js
- app/templates/about.hbs
- app/templates/home.hbs
- app/templates/my_orders.hbs
https://jira.crossroads.org.hk/browse/GCW-2987
FEATURE: Makes the back button of Request_purpose page work appropriately.
> GCW-2987-Added refactoring for back button in request_purpose page

- app/controllers/orders/goods.js
- app/templates/orders/goods.hbs
https://jira.crossroads.org.hk/browse/GCW-2919
fixed live updating item-details on goods page
> GCW-2919 fixed live updating item-details on goods page

- app/models/package_set.js
- app/templates/search_goods.hbs
This bug only happens when images are missing, meaning staging is very vulnerable, but prod luckily isn't. Nevertheless, I will fast-track this to prod to be safe.
> GCW-3161 missing function

- app/controllers/orders/goods.js
- app/locales/zh/translations.js
- app/models/package_set.js
- app/styles/_search.scss
- app/templates/order/search_code.hbs
- app/templates/orders/goods.hbs
- app/templates/search_goods.hbs
- package.json
- [GCW-3161](https://jira.crossroads.org.hk/browse/GCW-3161) Browse: While browsing, certain item categories can't be accessed and attempting to do so causes empty pages when browsing the site.
- [GCW-2274](https://jira.crossroads.org.hk/browse/GCW-2274) Browse: The back button on the Goods Type page is misaligned
- [GCW-2919](https://jira.crossroads.org.hk/browse/GCW-2919) Browse: Issues with changing an item's category in Stock
> [Release] 0.8.4 - Bug fixes

- app/routes/request_purpose.js
https://jira.crossroads.org.hk/browse/GCW-2537
BUG: Change of value of district back to english got fixed
> Defect of Value changing to english fixed

- app/controllers/orders/goods.js
https://jira.crossroads.org.hk/browse/GCW-3030
Removes items successfully from orders
> GCW-3030-Cancelled items can now be removed from Orders in browse app

- app/controllers/orders/conversation.js
- app/models/message.js
- app/models/order.js
- app/serializers/application.js
https://jira.crossroads.org.hk/browse/GCW-3132
This adds the polymorphic relationship changes as done in the API 
https://github.com/crossroads/api.goodcity/pull/999
> GCW-3132 Adding polymorphic relation changes

- app/templates/orders/_message_template.hbs
> Fix display of mentioned user

- app/serializers/application.js
https://jira.crossroads.org.hk/browse/GCW-3203
Fix the error in Client Information Page
Client Information
> GCW-3203 Fix Client Information Page

- app/controllers/application.js
- app/styles/_cart_sidebar.scss
- app/styles/_sidebar.scss
- app/styles/templates/_home.scss
- app/templates/_cart_truck_icon.hbs
https://jira.crossroads.org.hk/browse/GCW-2923
Fixed UI of cart-icon with cart-count
> GCW-2923 fixed UI of cart-icon with cart-count

- app/components/book-appointment.js
- app/controllers/about.js
- app/controllers/home.js
- app/services/settings.js
- app/styles/_about.scss
- app/templates/about.hbs
- app/templates/components/book-appointment.hbs
- app/templates/home.hbs
Ticket: https://jira.crossroads.org.hk/browse/GCW-3229
This PR adds the following `goodcity_settings` :
- browse.appointment_warning_en
- browse.appointment_warning_zh_tw
- browse.online_order_warning_en
- browse.online_order_warning_zh_tw
- browse.allow_appointments
They allow displaying warnings on the home page, and disabling appointments
> GCW-3229 Settings to disable appointments

- app/components/quantity-widget.js
- app/controllers/application.js
- app/controllers/order/confirm_booking.js
- app/controllers/orders/goods.js
- app/controllers/package_set.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/mixins/quantity_update.js
- app/models/orders_package.js
- app/models/package.js
- app/models/package_set.js
- app/models/requested_package.js
- app/routes/package.js
- app/services/cart.js
- app/styles/_cart_sidebar.scss
- app/styles/_request_purpose.scss
- app/styles/app.scss
- app/styles/components/_quantity-widget.scss
- app/styles/confirm_booking.scss
- app/styles/templates/_item.scss
- app/templates/cart_content/_full_view.hbs
- app/templates/cart_content/_items.hbs
- app/templates/components/quantity-widget.hbs
- app/templates/order/_embed_cart_detail.hbs
- app/templates/orders/goods.hbs
- app/templates/package_set.hbs
https://jira.crossroads.org.hk/browse/GCW-3186
FEATURE: Adds quantity widget feature
> GCW-3186 Add quantity indicator for items

- app/components/quantity-widget.js
- app/controllers/package_set.js
- app/services/cart.js
- app/styles/components/_quantity-widget.scss
- app/templates/components/quantity-widget.hbs
https://jira.crossroads.org.hk/browse/GCW-3186
Fixes for breaking of the live updates of quantity in quantity feature and it also fix the issue mentioned in https://jira.crossroads.org.hk/browse/GCW-3031
> Fixes for breaking of the live updates of quantity in quantity feature

- app/routes/browse.js
https://jira.crossroads.org.hk/browse/GCW-3010
fixed display of menu-bar on browse page
> GCW-3010 fixed display of menu-bar on browse page

- app/controllers/package_set.js
- app/models/permission.js
- app/models/role.js
- app/models/role_permission.js
- app/models/user.js
- app/templates/package_set.hbs
https://jira.crossroads.org.hk/browse/GCW-3253
FEATURE: Package link to stock should show based on permissions
> GCW-3253-Package link based on permissions

- app/models/user.js
Fix typo error for  CurrentUserRole to  CurrentUserRoles
> Typo Error fix for CurrentUserRoles

- app/controllers/application.js
- app/controllers/order/confirm_booking.js
- app/controllers/package_set.js
- app/mixins/quantity_update.js
- app/styles/_cart_sidebar.scss
- app/styles/confirm_booking.scss
- app/templates/cart_content/_full_view.hbs
- app/templates/cart_content/_items.hbs
- app/templates/order/_embed_cart_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3186
BUG: QA fix for quantity widget
> QA fix for quantity widget

- app/controllers/account_details.js
- app/models/organisations_user.js
- app/models/user.js
- app/services/session.js
https://jira.crossroads.org.hk/browse/GCW-3275
- Remove references to the charity role
- Introduce the 'status' column to OrganisationsUsers
- Account details page
> GCW-3275 Remove the charity role

- app/controllers/account_details.js
- app/templates/account_details.hbs
https://jira.crossroads.org.hk/browse/GCW-3326
The PR fixes the country code note being sent for user mobile and the display of proper error message from API.
There is no change in the `.hbs` and is just auto-formatting done by my editor 🙈
> GCW 3326 Account Details Page

- app/controllers/account_details.js
https://jira.crossroads.org.hk/browse/GCW-3326
> Fix on empty mobile number

- app/services/cart.js
https://jira.crossroads.org.hk/browse/GCW-3343
fixed issue with removing item from guest-user's cart
> GCW-3343 fixed issue with removing item from guest-user's cart

- app/templates/request_purpose.hbs
https://jira.crossroads.org.hk/browse/GCW-3310
BUG: Editing no of people helped in the request purpose page causing something went wrong error fix
> GCW-3310-Editing no of people helped in the request purpose page causing something went wrong error fix

- app/adapters/application.js
- app/controllers/search_organisation.js
- app/templates/search_organisation.hbs
https://jira.crossroads.org.hk/browse/GCW-3402
This PR fixes broken organisation search for account_details page along with pagination on organisation search page.
> GCW-3402- Search organisation broken for Organisation search for adding in Account Details page.

- app/components/item-thumbnail-view.js
- app/components/offers-block.js
- app/controllers/offers/index.js
- app/controllers/offers/messages.js
- app/router.js
- app/routes/offers/detail.js
- app/routes/offers/index.js
- app/routes/offers/messages.js
- app/services/api-base-service.js
- app/services/offer-service.js
- app/styles/_my_dashboard.scss
- app/styles/app.scss
- app/styles/templates/_offers.scss
- app/styles/templates/_package_category.scss
- app/templates/components/item-thumbnail-view.hbs
- app/templates/components/offers-block.hbs
- app/templates/home.hbs
- app/templates/offers/_offers_tabs.hbs
- app/templates/offers/detail.hbs
- app/templates/offers/index.hbs
- app/templates/offers/messages.hbs
- config/environment.js
- yarn.lock
https://jira.crossroads.org.hk/browse/GCW-3405
This PR adds offers listing shared from admin API. It is using the `V2` API. It has the following pages:
- Offers list
- Detail offer page
- Chat page for the offer.
> GCW-3405-User can responds to offers

- app/models/package.js
- app/templates/components/cloudinary-image-tag.hbs
- app/templates/package_set.hbs
https://jira.crossroads.org.hk/browse/GCW-3446
FEATURE: Adding Chinese Description to Packages in Browse App
> GCW-3446 Adding Chinese Description for packages in browse app

- app/styles/templates/_package_category.scss
- app/templates/components/item-thumbnail-view.hbs
- app/templates/offers/detail.hbs
- app/templates/offers/index.hbs
This PR adds an overlay to display notes on Offers Images.
> FIX=> Overlay added for Offers images

- app/controllers/search_organisation.js
- app/styles/_search.scss
- app/templates/search_organisation.hbs
https://jira.crossroads.org.hk/browse/GCW-3402
BUG: As mentioned here https://jira.crossroads.org.hk/browse/GCW-3402?focusedCommentId=42026&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42026
> GCW-3402-Changes added to address QA comments in organisation search user page

- app/services/order-service.js
https://jira.crossroads.org.hk/browse/GCW-3472
Adds description field in the payload
> GCW-3472 Appointment request descriptions are not saved

- app/services/order-service.js
https://jira.crossroads.org.hk/browse/GCW-3472
Fix issues reported by Tims
> GCW-3472 Add description in request

- app/routes/offers/messages.js
This PR fixes hiding of side panel after login into offers chat tab.
> FIX=> Shareables side panel fix for offers chat tab

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/offers/messages.js
- app/styles/_messages.scss
- app/templates/offers/_offers_tabs.hbs
- app/templates/offers/messages.hbs
https://jira.crossroads.org.hk/browse/GCW-3482
This PR adds the check for user roles if there are any roles the user is restricted from accessing message UI on offers.
> GCW-3482- Shareable Chat - Prevent Staff members from using it

- app/controllers/offers/messages.js
- app/routes/offers/messages.js
- app/services/session.js
This PR fixes live update access of offers message screen.
Please review this PR.
> GCW- 3482-chat access userRoles live update

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/styles/templates/_offers.scss
- app/templates/components/item-thumbnail-view.hbs
- app/templates/components/offers-block.hbs
- app/templates/offers/detail.hbs
Adding change in shareable feature in browse app
> GCW-3490-Enhancement in shared offer feature

- app/models/package.js
- app/models/package_set.js
> Removing async relationship between package and packageSet

- app/components/change-phone-number-overlay.js
- app/components/popup-overlay.js
- app/controllers/my_account.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/services/account-service.js
- app/services/api-base-service.js
- app/styles/app.scss
- app/styles/components/_change_phone_number_overlay.scss
- app/styles/components/_popup-overlay.scss
- app/templates/components/change-phone-number-overlay.hbs
- app/templates/my_account.hbs
https://jira.crossroads.org.hk/browse/GCW-3537
Provides ability for the charity user to change phone number
> GCW-3537 Modify Phone Number

- app/components/change-phone-number-overlay.js
- app/styles/_my_dashboard.scss
- app/styles/components/_change_phone_number_overlay.scss
- app/styles/components/_popup-overlay.scss
- app/templates/components/change-phone-number-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3537
- Fix QA reported issues
- Enhance UI
> GCW-3573 Add UI Enhancements

- app/components/change-phone-number-overlay.js
- app/styles/_my_account.scss
- app/styles/account_details.scss
- app/styles/components/_change_phone_number_overlay.scss
- app/templates/components/change-phone-number-overlay.hbs
- app/templates/my_account.hbs
https://jira.crossroads.org.hk/browse/GCW-3537
Updated UI for update mobile screen
> GCW-3537 updated UI for update mobile screen

- app/models/message.js
- app/services/messages.js
https://jira.crossroads.org.hk/browse/GCW-3201?focusedCommentId=45379&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-45379
BUG: Adds public_id to the messages for helping in the route of offers in notification
> GCW -3201: Add public_id to message model

- app/controllers/package.js
- app/templates/package_set.hbs
https://jira.crossroads.org.hk/browse/GCW-3341
Do not allow  to remove part of a set from the cart
> GCW-3341 - Fix issue while adding set to cart that makes the site non-functional

- app/controllers/account_details.js
- app/styles/account_details.scss
- app/templates/account_details.hbs
https://jira.crossroads.org.hk/browse/GCW-3345
Fix validation issue for user full name in accounts details page for browse app
> GCW-3345 - Fix validation issue for user info on account details page

- app/controllers/package_set.js
https://jira.crossroads.org.hk/browse/GCW-3341
FIxes cart issues for package-sets
> GCW-3341 Fix packageSet errors in cart while unpublishing packages

- app/routes/offers/messages.js
https://jira.crossroads.org.hk/browse/GCW-3662
Launch account-details page for incomplete user-profile when responding to offer-messages
> GCW-3662 Launch account-details page for incomplete user-profile when responding to offer-messages

- app/controllers/my_notifications.js
- app/controllers/offers/messages.js
- app/models/message.js
- app/models/offer_response.js
- app/routes/offers/messages.js
- app/services/messages.js
- app/templates/my_notifications.hbs
- app/templates/offers/messages.hbs
https://jira.crossroads.org.hk/browse/GCW-3663
FEATURE: Offer Responses Changes
> Gcw 3663 add offer response table

- app/components/item-thumbnail-view.js
- app/components/offers-block.js
- app/controllers/offers/messages.js
- app/routes/offers/detail.js
- app/routes/offers/messages.js
- app/services/offer-service.js
- app/styles/templates/_offers.scss
- app/templates/components/offers-block.hbs
- app/templates/offers/detail.hbs
- app/templates/offers/messages.hbs
https://jira.crossroads.org.hk/browse/GCW-3664
FEATURE: Alter UI logic of offer sharing
> GCW 3664 Alter UI logic of offer sharing

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/package_category.js
https://jira.crossroads.org.hk/browse/GCW-3125
redirect to browse page on invalid category
> GCW-3125 redirect to browse page on invalid category

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/offers/detail.js
- app/routes/offers/messages.js
- app/services/offer-service.js
- app/styles/components/_order-cards.scss
- app/styles/templates/_home.scss
- app/templates/components/offers-block.hbs
- app/templates/offers/detail.hbs
- app/templates/offers/messages.hbs
Changes done:
1) Add respond offer/ view offer button as per need of login
2) Changed the routes for view offer and respond t offer
3) Added header of **Details of offer**
4) Redirected for the authorized user in offer/details page
5) Item / Offer Description in Chinese language handled
>  Changes for offer responses based on suggestion 

- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/styles/templates/_offers.scss
- app/templates/offers/messages.hbs
NOTE: https://jira.crossroads.org.hk/browse/GCW-3707
Removes offer details for offers that are unshared or deleted
> :bug: GCW-3707-Remove offer details for offers that is unshared or deleted

- app/controllers/offers/messages.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/routes/offers/messages.js
- app/templates/offers/messages.hbs
NOTE: https://jira.crossroads.org.hk/browse/GCW-3708
FEATURE: Improves the disabled chat message
> :bug: GCW-3708-Improve disabled chat message

- app/locales/zh/translations.js
https://jira.crossroads.org.hk/browse/GCW-3720
Adds more Chinese translations to the Browse app
> Translations updated

- app/styles/templates/_offers.scss
- app/templates/offers/detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3722
FEATURE: Add more information about items on offer details page
> GCW-3722- Add more details to offer details page

- app/controllers/my_notifications.js
- app/locales/en/translations.js
- app/locales/zh/translations.js
- app/services/messages.js
- app/templates/my_notifications.hbs
- app/templates/offers/messages.hbs
- app/templates/orders/goods.hbs
- package.json
Tickets affected:
GCW-3726
GCW-3566
GCW-3722
> [Release] 0.10.2

- app/styles/_static_pages.scss
- app/templates/faq.hbs
- app/templates/privacy.hbs
- app/templates/terms.hbs
> FAQ in English
