app/controllers/subscription.js
Hi Team,
This PR fixes live update issue.
- When User is logged in to Browse App any any other order is updated on Stock App then Browse App shows that order on my_orders page with "something went wrong" pop up.
- This PR fixes this issue of live update.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2052
Please review it and let me know if any other changes are required.
Thanks
=> GCW-2052 Modification of order which is not created by current logged in user bug

circle.yml
Hi Team,
This PR is related to android building issue of jira ticket https://jira.crossroads.org.hk/browse/GCW-2038.
Circle CI build is failing at ios build because of which android build is not executed. To make it work android build steps are added before ios steps.
If any change is required, let me know.
Thanks.
=> android deployment steps added before ios deployment

app/templates/sidebar.hbs
Hi Team,
This PR fixes issue: crossroads logo is not visible on sidebar(mobile apps)
Please Review.
Thanks
=> #September2018Release1

app/routes/my_orders.js, app/templates/my_orders.hbs, config/environment.js
Hi Team,
This PR includes following changes
- Removes eager-loading for orders and adds lazy loading(loads on page visit)
- Removes Item count from my_orders page
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2195
Last change should be fixed in GCW-2187 => https://jira.crossroads.org.hk/browse/GCW-2187
Please review it and let me know if any other changes are required.
Thanks
=> GCW-2195 Lazy shallow order loading

.circleci/config.yml
Hi Team,
Disabling ios build for now. We can enable it whenever its actually needed and again we can disable it until we find solution for billing and extra build time 
Thanks.
=> disable ios build

app/templates/order/goods_details.hbs
Hi Team,
This PR fixes issue email id not appearing in to field of mail-to.
https://jira.crossroads.org.hk/browse/GCW-2275
Please review.
Thanks.
=> fix mail to link

app/controllers/order/transport_details.js
Hi team, 
One user of Browse had an issue where he/she couldn't proceed pas the transport details page.
After testing I noticed the error comes from tying to save the contact address to the order :
`this.get('order.orderTransport.contact.address.id');` would return undefined _even though_ the data was returned by the server correctly.
I suspect if might be related to those issues :
- https://github.com/emberjs/data/issues/2496
- https://github.com/emberjs/data/issues/5313
why we are seeing it only now, I'm not sure  ¯\\_(ツ)_/¯
I made a quick fix just to get it working for prod, but I am **not** happy with this 😄 😄 
--> any suggestions ? <--
I'm having a hard time remembering why we had to store the address on the order. If it is required, then couldn't `order.addressId` be computed on the …
=> Workaround for issue where addressId was undefined

app/controllers/order/client_information.js, app/locales/en/translations.js, app/locales/zh/translations.js, app/models/order.js, app/templates/order/schedule_details.hbs, app/templates/request_purpose.hbs, bower.json, tests/acceptance/book-appointment-test.js
Somehow there was the following condition : 
```javascript
if (isClientInformation) {
this.transitionToRoute('order.goods_details', orderId, { queryParams: { fromClientInformation: true }});
}
```
which doesn't make sense, I suspect it's during a merge/conflict that it stayed there. This PR just removes it (and changes the title of a page as per requirements)
=> Fix redirection from client_information

package.json, yarn.lock
This PR removes Jshint
because we're using `https://www.npmjs.com/package/lint-staged` now for auto linting while committing.
=> Remove jshint

app/controllers/application.js
Hello team is PR fixes a minor issue, where if there are no items in cart, on clicking submit button it should show the message box asking to add items to the cart, instead of redirecting to the account_details.
Thanks
=> Fix minor issue when empty cart it should not go to account details if clicked on submit.

app/instance-initializers/subscription.js, app/services/subscription.js
A lot of logic was stripped out of the old `subscription.js` , the handling of this case seems to have disappeared along with it. I'm therefore adding it back
=> Live updates : Remove package on unpublish

app/controllers/account_details.js
Hi Team,
This PR fixes issue of account details form submission throwing an invalid mobile number error and allows to submit the form even if the mobile number field is blank as per requirement.
Please review.
Thanks.
=> GCW-2550 fix account details submission do not work if mobile is blank

app/controllers/application.js, app/controllers/my_orders.js, app/models/order.js, app/templates/my_orders.hbs, app/utils/helpers.js
Some edge cases appeared when live updates came into play (with the new api changes), we now fetch the record before navigating to the details page.
The detail pages know not to re-fetch a record that is already loaded.
It's important to make at least one findRecord call to populate everything we need, it's hard to move it to the details route because it is inherited by sub-pages, which risks causing multiple unneeded downloads (not totally convinced about this approach)
=> Fully load an order before navigating to the detail page

app/controllers/application.js
Earlier we were using `window.location.pathname`
but `pathname` returns `"/android_asset/www/index.html"` in case of android app. and hence the issue 
and `pathname` returns `"/page_name"` in case of web
`href` will return `"file:///android_asset/www/index.html#/request_purpose?bookAppointment=true"`
in case of mobile app
and will return `"http://localhost:4202/request_purpose?bookAppointment=true"`
in both case it will serve the purpose. So please review this, and let me know if any changes if required.
=> fix pages shifting to right

app/controllers/order/schedule_details.js, app/models/goodcity_setting.js, app/services/settings.js, config/environment.js
If you haven't yet reviewed the new server changes, please do so first here : https://github.com/crossroads/api.goodcity/pull/750 , things will make more sense.
This PR adds a `settings` service, which is just a combination of key value pairs which the app can read. The catch is that if one of those settings has been defined on the backend, it will use that value instead (basically we are able to override configs remotely).
Currently I've only added on configuration : `browse.online_order.timeslots.booking_margin`
It defines a margin of days before which users can book their online order in. It was based on a comment from Nokia, she mentioned that if someone books for the next day, that wouldn't give the staff enough days to prepare.
That margin will certainly change in the future, so …
=> Settings service + OnlineOrder booking margin config

app/components/app-canvas.js, app/components/image-preview.js, app/components/observe-screen-resize.js, app/controllers/application.js, app/routes/home.js, app/services/screenresize.js, app/templates/application.hbs
We would have those weird moments where the sidebar would appear without being triggered, this PR aims the fix that.
The problem came from the fact that there were conflicts over CSS classes that were bound via ember's `{{ }}` interpolation, which were also being manipulated through jQuery.
Ideally, we would **_never_** use `$(...)`.
However, because that part of the code is based on foundation, things already happen in the background out of our control and we're kinda forced to use it sadly 😢
- I removed the bound property that is already being controller manually through the screen resize observer
- removed as much DOM manipulation code I could, we really don't want any in the app
- removed some old unused properties and fixed some that were simply not working
- renamed a lot of …
=> Fix weird sidebar behaviours

app/locales/en/translations.js, app/locales/zh/translations.js, app/routes/application.js, app/routes/authorize.js
Currrently, if user is logged out and tries to visit any page, we show "You must login!" modal, which looks rude, so this PR removes that modal, and automatically redirects them to the login page.
Keeping in mind which the user was trying to visit, post login user is redirected to that page.
=> redirect-users-to-login-instead-of-showing-modal

app/templates/request/hk_identity_type_details.hbs, app/templates/request/rbcl_identity_type_details.hbs
Fixed the issue that is mentioned in the below ticket where previously the field was not showing a warning message:
https://jira.crossroads.org.hk/browse/GCW-2565
=> Fix IE11 issue the ID number field in client info

app/styles/templates/_item.scss
Hi Team,
This PR fixes cross icon on image is not clickable on ios mobile safari. 
https://jira.crossroads.org.hk/browse/GCW-2676
Please review.
Thanks.
=> fix cross icon for ios safari

app/services/cart.js, app/services/session.js, tests/acceptance/account_details-test.js, tests/acceptance/book-appointment-test.js, tests/acceptance/cart-test.js, tests/acceptance/my-dashboard-test.js
In order to save the packages that were selected while offline, we need the user ID.
But the current logic does `if (authToken) { ... }` , however the authToken doesn't guarantee that the user profile was downloaded yet. This aims to fix that.
Also, since I got the chance. I also changed the way the current user info is retrieved from the store.
We currently had the currentUser equal to `this.get("store").peekAll("user").get("firstObject")` . It's obviously flaky and wrong to assume that the first user in the data is the logged in user.
So I've made it that the current user is dependant on the ID that we fetch when we load the profile !
=> Cart waits for user profile to be loaded

.ember-cli, app/controllers/item.js, app/locales/en/translations.js, app/locales/zh/translations.js, app/routes/package.js, app/styles/_search.scss, app/styles/templates/_item.scss, app/templates/item.hbs
This PR fixes one issue which TIM reported, that on clicking item from search page, the back link appears as category name, but it takes back to search page. 
So changes have been made such that, when user comes from search_page, it'll show "Back to search" otherwise it will show category name as the back link.
Also, this PR contains some css fixes for search page. Please review. 
Thanks
=> change the backlink name on item page to "Back to Search"

app/controllers/application.js, app/models/package.js
Here's the fix for one of the `account_details` page.
Note: I think the whole navigation flow needs some work, but making a "hotfix", since we're a bit short on time before the launch event.
A lot of this is hard to see when reading to code, because we need to follow the transitions all the way, but here's a breakdown of what was happening:
For a new user, the current logging flow looked like this : 
`[auth page] -> [verification page] -> [account details page]`
And the "submit cart" flow as a `guest` looked like this: 
`[login flow] -> [account details page] -> [request_purpose]`
So If I write the whole thing it essentially resulted in this :
`[auth page] -> [verification page] -> [account details page] -> [account details page] -> [request_purpose]`
The `account_details` page would be …
=> Quick fix for the account details page navigation bug

app/controllers/submitted_order_selection.js
Hi Team,
This fix is for IE on Order selection UI. Replaced `includes` with `indexOf`.
=> FIX=> IE fix for order selection UI

yarn.lock
Hi Team,
This PR contains the yarn.lock file needed to sync goodcity-lib . with the browse app.
Please review.
=> GCW-2298 adding yarn lock file to sync with goodcity lib

app/styles/components/_add-request.scss, app/templates/order/goods_details.hbs
https://jira.crossroads.org.hk/browse/GCW-2912
BUG: Specify bug 
This PR fixes the alignment issue of The 'Request more goods' text/button on the goods_details page.
Screenshots:
Please review
=> GCW-2912 fixed alignement issue of add more button

app/templates/cart_content/_full_view.hbs
https://jira.crossroads.org.hk/browse/GCW-2994
Bug: 
This PR uses the hidecart action to for findout more item button to solve home redirection issue.
Please review
=> GCW-2994 used hide cart action for find out more item button

app/templates/account_details.hbs
Moving this urgently to prod !
The email field was broken due to `value=email` appearing twice in the ember component
=> Fix broken email field

app/controllers/application.js, app/controllers/item.js, app/locales/en/translations.js, app/locales/zh/translations.js, app/models/package.js, app/styles/templates/_item.scss, app/templates/cart_content/_full_view.hbs, app/templates/item.hbs
https://jira.crossroads.org.hk/browse/GCW-2985
This PR fixes two issue:
1. In the Browse app, it does not fetch the items with zero quantity in the response. But there are some cases where item page is open in browser and it is dispatched from the stock app, which changes the quantity to zero but the `Request Item` button is still active.
Fixed this issue by disabling the `Request Item` button 
2. On cart show page `/cart`, even though there are no items in cart, `Submit order` button is active and which shows message on click as 
This seems bit confusing, as User have not added any item at all. 
Fixed it by disabling the `submit order` button.
`/cart` and item page
=> Gcw 2985 Fixed addition of zero quantity item in cart

app/controllers/application.js, app/controllers/item.js, app/services/cart.js
https://jira.crossroads.org.hk/browse/GCW-2920
**Issue 1:**
When on click of `Request Item` gives any error for any edge case, it still adds that item to cart. And allows to create order and eventually creates order with no item.
Fix: Unload requested-package record from cart if receive any error from backend
**Issue 2**
For logged-in users, while cart submit, it does not check item's availability. And allows to create order with no item.
Fix: For logged-in user, updated condition to check for cart having items and availability of those items. 
Cart page
=>  GCW-2920 avoid creation of empty order

app/templates/orders/_message_template.hbs
https://jira.crossroads.org.hk/browse/GCW-3029
Whenever ussr entered a blank space in the chat section the chat setup was breaking and was directing user towards homepage with the popup saying Something went wrong. 
Fix: Now it errors error if the message box is empty or user enters blank spaces and try to send it.
=> GCW-3029-Blank message breaking the chat issue is fixed

app/styles/_my_orders.scss
https://jira.crossroads.org.hk/browse/GCW-3034
The button find items to request was not having a bg and which was added in this PR
=> GCW-3034-UI bug related to find items to request button is now working fine

app/models/item.js, app/models/orders_package.js, app/models/package.js, tests/acceptance/item-test.js, tests/factories/package.js, tests/unit/models/item-test.js, tests/unit/models/order-test.js, tests/unit/models/orders_packages-test.js, tests/unit/models/package-test.js, tests/unit/models/package-type-test.js
This PR is dependant on https://github.com/crossroads/api.goodcity/pull/926
- Addition of the following fields to the `item` model (which is actually a `package`)
* `availableQuantity`
* `onHandQuantity`
* `dispatchedQuantity`
* `designatedQuantity`
- The `quantity` field is now an alias to `availableQuantity` (as a temporary safeguard)
- Changed all the reads of old quantities I found to the new properties
=> Remove quantity field

app/controllers/orders/conversation.js
https://jira.crossroads.org.hk/browse/GCW-3029
It fixes the edge case of chat feature. Whenever anyone tries to press spacebar and send button simultsneously in the chatbox .Something went error does not pop-up and no message is created in the store
=> Spacebar and send button pressed together dont send error now

app/styles/_my_orders.scss, app/templates/order/_cancel_order.hbs
https://jira.crossroads.org.hk/browse/GCW-2601
fixed UI at cancel transport details message buttons
=> GCW-2601 fixed UI at cancel transport details message buttons

app/controllers/order/schedule_details.js, package.json
We have a setting on goodcity called `booking_margin`. That margin prevents people from selecting a pickup date on the same day or the days immediatly after. Essentially giving time for the staff to prepare the order.
Currently we do a `slice(bookingMargin)` on the days available. But if the first few days are holidays then we're not actually cutting any business days out.
This PR fixes that, by applying the `slice` to business days only.
+ general refactoring of the method
=> Release[0.8.2] Online order booking margin fix

app/templates/components/image-preview.hbs
https://jira.crossroads.org.hk/browse/GCW-2893
Fixes the 'Something went wrong' pop-up message on clicking the package image if there is no image present
Browse > View Package
=> GCW-2893 Fix error on vieweing package with no image

app/controllers/order/schedule_details.js, app/controllers/request_purpose.js, app/locales/en/translations.js, app/locales/zh/translations.js, app/mixins/cancel_order.js
https://jira.crossroads.org.hk/browse/GCW-2909
This Fixes the scenario where the user is able to edit the order even after its cancelled
Browse -> Request Purpose and Appointment screens
https://github.com/crossroads/api.goodcity/pull/997
=> GCW-2909 Fix editing the order after cancelling it

app/locales/en/translations.js, app/locales/zh/translations.js, app/templates/about.hbs, app/templates/home.hbs
https://jira.crossroads.org.hk/browse/GCW-3140
Removes the special alert notices on home page and about page related to COVID-19 closures.
=> Removing COVID-19 notices

app/styles/_search.scss, app/templates/order/search_code.hbs
https://jira.crossroads.org.hk/browse/GCW-2274
BUG: FIxed the misaligned button in chrome as well as in IE and edge browser
=> GCW-2274-Back Button fixed in goods type selection page

app/styles/_search.scss, app/templates/order/search_code.hbs
https://jira.crossroads.org.hk/browse/GCW-2274?focusedCommentId=38516&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38516
BUG: Back '<' symbol now matches the symbol of other pages
ScreenShots:
=> GCW-2274-Add css changes for the back button

.github/workflows/release-notes.yml, app/routes/request_purpose.js, app/templates/components/add-request.hbs, fastlane/Fastfile, package.json
**Generated on:** 2020-6-10 16:11:40
**Repository:** `git@github.com:crossroads/browse.goodcity.git`
- [GCW-2848](https://jira.crossroads.org.hk/browse/GCW-2848) Stock: While creating a new order, it's possible to complete the order with an invalid goods type.
- [GCW-2537](https://jira.crossroads.org.hk/browse/GCW-2537) Browse-app(Staging): District Name changing back to English on the Chinese page.
=> [Release] Browse v0.8.5

app/controllers/account_details.js
https://jira.crossroads.org.hk/browse/GCW-3246
On Charities, If an existing mobile number is entered on the Account Details page, an incorrect message appears: "Email has already been taken". This will handle the scenario.
=> Fix destroy component when the component is not present in the DOM

app/routes/orders/booking.js
https://jira.crossroads.org.hk/browse/GCW-2924
BUG: If the user scrolls down on the My Dashboard page before selecting an order, the page will still be scrolled down on the order page fix
=> GCW-2924 Scrollbar issue in booking page resolved

.circleci/config.yml, Rakefile, fastlane/Fastfile
https://jira.crossroads.org.hk/browse/GCW-3305
FEATURE: Deprecates use of `APP_VERSION` environment variable in the app builds. Delegates to `package.json` instead.
NOTE: Previously, bumping the app version required updating `package.json` and updating `APP_VERSION` in CircleCI. This was was unnecessary duplication and made the builds less automated. After this PR is merged, version will be set entirely from code in the projects `package.json` file and we can delete `APP_VERSION` from CircleCI
- iOS App Store app version
- Google Play app version
=> GCW-3305-Deprecate usage of APP_VERSION in browse app

app/controllers/order/schedule_details.js
https://jira.crossroads.org.hk/browse/GCW-3157
BUG: If a Special Date is set up when an order is already set up with that date, when attempting to change that date, the date will still be available fix
=> GCW-3157-Appointment date edge case fix

app/services/session.js
On login,  user data was not loaded in the local storage hence cloud cart could not sync and the cart seems empty. When the user tries to add a package already present in the cloud cart (requested packages) the glimmer issue occurs
=> GCW-3543-Glimmer issue fix

app/routes/application.js
https://jira.crossroads.org.hk/browse/GCW-3513
Resolved bug.
Allow User to open multiple offers in different tabs when User is not logged in and do not auto redirect to login page
=> GCW-3513 - If a user is not logged in, allow user to stay in offers page

app/controllers/package.js
https://jira.crossroads.org.hk/browse/GCW-3341
Resolve below edge case
First create items and make sets in stock app.
Then publish one item of set view it in browse app
now later make the other item of set publish and then (without reloading) just go back and check the set and then try to add set in cart and we can see the request item button not disables for individual item
=> GCW-3341 Disable "add item" button for individual item of set when set has more than 1 items
